# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa22555ea045212bf54b205e530f42f618e81ff55a149bed5125bca3dd9a4fb6f7f3c4fe48233f94fc4efa16bfcb840e2c7b9e02c3bddd53ff8474b3d464e9bf

test:
  secret_key_base: c8c5a983091a5a8e9dfc07f42b6d99bd816af741a1597ff68d63403d9b4470152d9c560148b7baed8c13cb3866a558ddb3bb77a9657877652e7881b44fa65e62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
